import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import path from 'node:path';
const require = createRequire(import.meta.url);
const esbuild = require(process.env.ESBUILD_MODULE || 'esbuild');
const client = await esbuild.build({ entryPoints: [fileURLToPath(new URL('web/app.mjs', import.meta.url))], bundle: true,
  format: 'esm', platform: 'browser', target: 'es2022', external: ['/keys.mjs'], write: false, metafile: true, legalComments: 'none' });
const html = await readFile(new URL('web/index.html', import.meta.url), 'utf8');
const assets = {
  '/chat': ['text/html; charset=utf-8', html], '/chat/': ['text/html; charset=utf-8', html],
  '/chat/style.css': ['text/css; charset=utf-8', await readFile(new URL('web/style.css', import.meta.url), 'utf8')],
  '/chat/app.mjs': ['text/javascript; charset=utf-8', client.outputFiles[0].text],
};
await writeFile(new URL('assets.generated.mjs', import.meta.url), '// Generated by build.mjs.\nexport const ASSETS = ' + JSON.stringify(assets, null, 2) + ';\n');
const server = await esbuild.build({ entryPoints: [fileURLToPath(new URL('worker.mjs', import.meta.url))], bundle: true, format: 'esm',
  platform: 'browser', target: 'es2022', metafile: true, outfile: fileURLToPath(new URL('worker-upload.mjs', import.meta.url)), legalComments: 'none' });
const digest = bytes => createHash('sha256').update(bytes).digest('hex');
const root = fileURLToPath(new URL('../../', import.meta.url));
const inputs = new Set([...Object.keys(client.metafile.inputs), ...Object.keys(server.metafile.inputs),
  ...['web/index.html', 'web/style.css', 'build.mjs', 'wrangler.jsonc'].map(p => fileURLToPath(new URL(p, import.meta.url)))]);
const hashes = {};
for (const input of [...inputs].sort()) hashes[path.relative(root, path.resolve(input))] = digest(await readFile(input));
await writeFile(new URL('build-inputs.json', import.meta.url), JSON.stringify(hashes, null, 2) + '\n');
await writeFile(new URL('ARTIFACT.sha256', import.meta.url), digest(await readFile(new URL('worker-upload.mjs', import.meta.url))) + '  worker-upload.mjs\n');
console.log('Built local signed-chat candidate, including unchanged pairing assets. Nothing deployed; AI flags remain closed.');
